CREATE DATABASE QLBanHang
GO
CREATE TABLE VATTU
(
MaVTu CHAR(4) PRIMARY KEY,
TenVTu NVARCHAR(100),
DvTinh NVARCHAR(10),
PhanTram REAL
)
GO
CREATE TABLE NHACC
(
MaNhaCc CHAR(3) PRIMARY KEY,
TenNhaCc NVARCHAR(100),
DiaChi NVARCHAR(200),
DienThoai VARCHAR(20)
)
GO
CREATE TABLE DONDH
(
SoDh CHAR(4) NOT NULL PRIMARY KEY,
NgayDh DATETIME,
MaNhaCc CHAR(3),
CONSTRAINT FK_MaNhaCc FOREIGN KEY (MaNhaCc) REFERENCES NHACC(MaNhaCc)
ON DELETE CASCADE
ON UPDATE CASCADE
)
GO
DROP TABLE DONDH
GO
CREATE TABLE CTDONDH
(
SoDh CHAR(4) NOT NULL,
MaVTu CHAR(4) NOT NULL,
SlDat INT,
CONSTRAINT PK_CTDONDH PRIMARY KEY(SoDh, MaVTu),
CONSTRAINT FK_CTDONDH_SoDh FOREIGN KEY (SoDh) REFERENCES DONDH(SoDh) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FK_CTDONDH_MaVTu FOREIGN KEY (MaVTu) REFERENCES VATTU(MaVTu) ON DELETE CASCADE ON UPDATE CASCADE
)
GO
DROP TABLE CTDONDH




